(()=>{
  const CACHE='bible-text-v1';const VERSION='offline-bible-v1';const DONE_KEY='bible-offline-version';const statusEl=document.getElementById('status');
  function showStatus(text){if(!statusEl)return;statusEl.hidden=false;statusEl.textContent=text}function hideStatus(){if(statusEl)statusEl.hidden=true}async function registerWorker(){if(!('serviceWorker'in navigator))return;try{await navigator.serviceWorker.register('./service-worker.js')}catch{}}
  async function downloadBible(){if(!('caches'in window)||!Array.isArray(window.books||books))return;if(localStorage.getItem(DONE_KEY)===VERSION){hideStatus();return}if(!navigator.onLine){showStatus('Offline · downloaded books remain available');return}const allBooks=window.books||books,urls=[];for(const b of allBooks)for(let ch=1;ch<=b.chapters;ch++)urls.push(`${DATA_ROOT}/${b.id}/${ch}.json`);const cache=await caches.open(CACHE);let done=0,failed=0,next=0;showStatus('Preparing Bible for offline reading…');async function worker(){while(next<urls.length){const url=urls[next++];try{const already=await cache.match(url);if(!already){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));await cache.put(url,r.clone())}}catch{failed++}done++;if(done===1||done%25===0||done===urls.length)showStatus(`Preparing offline Bible · ${Math.round(done/urls.length*100)}%`)}}await Promise.all(Array.from({length:6},worker));if(failed===0){localStorage.setItem(DONE_KEY,VERSION);showStatus('Offline Bible ready');setTimeout(hideStatus,1800)}else showStatus('Offline download paused · it will continue next time you are online')}
  function applyYHWH(root=document){const lordWords=[...root.querySelectorAll?.('.word[data-strong="H3068"]')||[]].filter(el=>/^LORD[.,;:!?]?$/i.test(el.dataset.raw||''));for(const el of lordWords){const punctuation=(el.dataset.raw||'').match(/[.,;:!?]+$/)?.[0]||'';el.dataset.raw='YHWH'+punctuation;el.textContent='YHWH'+punctuation;let prev=el.previousElementSibling;if(prev?.classList.contains('word')&&prev.dataset.strong==='H3068'&&/^the$/i.test(prev.dataset.raw||'')){const between=prev.nextSibling;prev.remove();if(between?.nodeType===Node.TEXT_NODE&&/^\s+$/.test(between.nodeValue||''))between.remove()}}}
  const reader=document.getElementById('reader');if(reader){applyYHWH(reader);new MutationObserver(()=>applyYHWH(reader)).observe(reader,{childList:true,subtree:true})}window.addEventListener('online',downloadBible);registerWorker().finally(()=>setTimeout(downloadBible,600));
})();
(()=>{
  const PALETTES={cedar:['#aebca5','#eee1c8','#304638','#c77f63'],sandy:['#e1cf99','#fff8e5','#422c18','#a9b982'],petals:['#aaaee0','#f7d7c8','#494e96','#eda5b5'],harbor:['#9fb7be','#f3eadb','#263e4b','#d58f79'],plum:['#b9a5b5','#f2e5cf','#51374e','#c7a24c'],meadow:['#b8c7a3','#f3ead4','#314536','#d4a35f'],ocean:['#92b6c2','#eef3ed','#234654','#e0a071'],rosewood:['#b9a2a1','#f1dfd2','#542f34','#c8896d'],midnight:['#10151b','#1b232c','#f3efe7','#b79ad8']};
  const names={cedar:'Cedar',sandy:'Sandy',petals:'Petals',harbor:'Harbor',plum:'Plum',meadow:'Meadow',ocean:'Ocean',rosewood:'Rosewood',midnight:'Midnight'};
  const style=document.createElement('style');style.textContent=`html[data-palette]{--bg:var(--palette-bg);--paper:var(--palette-paper);--text:var(--palette-text);--muted:color-mix(in srgb,var(--palette-text) 66%,var(--palette-bg));--line:color-mix(in srgb,var(--palette-text) 18%,var(--palette-bg));--accent:var(--palette-accent);--accent-2:var(--palette-accent);--accent-soft:color-mix(in srgb,var(--palette-accent) 18%,var(--palette-paper));--surface:color-mix(in srgb,var(--palette-paper) 82%,var(--palette-bg));--surface-strong:color-mix(in srgb,var(--palette-text) 10%,var(--palette-paper))}.theme-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.theme-choice{min-width:0;border:1px solid var(--line);background:var(--paper);color:var(--text);border-radius:14px;padding:10px 8px 9px;text-align:left;font-size:12px;font-weight:650}.theme-choice.selected{outline:2px solid var(--accent);outline-offset:1px}.theme-swatch{height:38px;border-radius:9px;margin-bottom:7px;display:grid;grid-template-columns:repeat(4,1fr);overflow:hidden;border:1px solid color-mix(in srgb,var(--text) 12%,transparent)}.theme-swatch i{display:block}@media(max-width:420px){.theme-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.append(style);
  function applyPalette(key){if(!PALETTES[key])key='cedar';const[bg,paper,text,accent]=PALETTES[key],root=document.documentElement;root.dataset.palette=key;root.style.setProperty('--palette-bg',bg);root.style.setProperty('--palette-paper',paper);root.style.setProperty('--palette-text',text);root.style.setProperty('--palette-accent',accent);const tc=document.getElementById('themeColor');if(tc)tc.content=bg;localStorage.setItem('bible-palette',key);document.querySelectorAll('.theme-choice').forEach(b=>b.classList.toggle('selected',b.dataset.palette===key))}
  const settings=document.getElementById('settingsBtn');if(settings){settings.textContent='⚙︎';settings.setAttribute('aria-label','Settings');settings.title='Settings'}
  const appearance=[...document.querySelectorAll('#settingsPanel .settings-section')].find(s=>s.querySelector('.settings-label')?.textContent.trim()==='Appearance');if(appearance){appearance.querySelector('.settings-label').textContent='Theme';const old=appearance.querySelector('.choice-row'),grid=document.createElement('div');grid.className='theme-grid';for(const[key,colors]of Object.entries(PALETTES)){const b=document.createElement('button');b.type='button';b.className='theme-choice';b.dataset.palette=key;b.innerHTML=`<span class="theme-swatch">${colors.map(c=>`<i style="background:${c}"></i>`).join('')}</span>${names[key]}`;b.onclick=()=>applyPalette(key);grid.append(b)}old?.replaceWith(grid)}applyPalette(localStorage.getItem('bible-palette')||'cedar');
})();
(()=>{
  const reader=document.getElementById('reader');if(!reader)return;
  const style=document.createElement('style');style.textContent=`.word.verse-peek{text-decoration-line:underline;text-decoration-color:var(--accent);text-decoration-thickness:1.5px;text-underline-offset:.2em}.verse-peek-bar{position:fixed;left:50%;bottom:calc(18px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:35;display:none;align-items:center;gap:10px;max-width:calc(100vw - 32px);background:var(--paper);color:var(--text);border:1px solid var(--line);border-radius:999px;padding:7px 8px 7px 14px;box-shadow:0 5px 22px #0003;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;font-size:13px}.verse-peek-bar.open{display:flex}.verse-peek-ref{font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.verse-copy{border:0;border-radius:999px;background:var(--accent);color:var(--bg);padding:8px 13px;font-weight:750;white-space:nowrap}.verse-copy.copied{background:var(--text);color:var(--paper)}`;document.head.append(style);
  const bar=document.createElement('div');bar.className='verse-peek-bar';bar.setAttribute('role','status');bar.innerHTML='<span class="verse-peek-ref"></span><button class="verse-copy" type="button">Copy</button>';document.body.append(bar);const refEl=bar.querySelector('.verse-peek-ref'),copyBtn=bar.querySelector('.verse-copy');let active=null,press=null;
  function clearPeek(){reader.querySelectorAll('.word.verse-peek').forEach(w=>w.classList.remove('verse-peek'));bar.classList.remove('open');copyBtn.textContent='Copy';copyBtn.classList.remove('copied');active=null}
  function verseWords(word){return [...reader.querySelectorAll(`.word[data-chapter="${CSS.escape(word.dataset.chapter)}"][data-verse="${CSS.escape(word.dataset.verse)}"]`)]}
  function cleanVerseText(words){return words.map(w=>w.dataset.raw||w.textContent).join(' ').replace(/\s+([,.;:!?])/g,'$1').replace(/([“‘])\s+/g,'$1').replace(/\s+([”’])/g,'$1').trim()}
  function showPeek(word){const words=verseWords(word);if(!words.length)return;const ref=word.dataset.ref||`${document.getElementById('bookName')?.textContent||''} ${word.dataset.chapter}:${word.dataset.verse}`;if(active?.ref===ref){clearPeek();return}clearPeek();words.forEach(w=>w.classList.add('verse-peek'));active={ref,text:cleanVerseText(words)};refEl.textContent=ref;bar.classList.add('open')}
  async function copyVerse(){if(!active)return;const out=`“${active.text}” ${active.ref}`;try{await navigator.clipboard.writeText(out);copyBtn.textContent='Copied';copyBtn.classList.add('copied');setTimeout(()=>{if(active){copyBtn.textContent='Copy';copyBtn.classList.remove('copied')}},1400)}catch{copyBtn.textContent='Copy failed'}}
  copyBtn.addEventListener('click',e=>{e.stopPropagation();copyVerse()});bar.addEventListener('pointerdown',e=>e.stopPropagation());
  reader.addEventListener('pointerdown',e=>{const w=e.target.closest('.word');if(!w||e.pointerType!=='touch')return;press={id:e.pointerId,word:w,x:e.clientX,y:e.clientY,t:performance.now(),moved:false}});
  reader.addEventListener('pointermove',e=>{if(!press||e.pointerId!==press.id)return;if(Math.hypot(e.clientX-press.x,e.clientY-press.y)>12)press.moved=true});
  reader.addEventListener('pointercancel',()=>press=null);
  reader.addEventListener('pointerup',e=>{if(!press||e.pointerId!==press.id)return;const p=press;press=null;const elapsed=performance.now()-p.t;if(!p.moved&&elapsed<400&&!document.getElementById('wordSheet')?.classList.contains('open'))showPeek(p.word)});
  reader.addEventListener('click',e=>{if(!matchMedia('(pointer:fine)').matches)return;const w=e.target.closest('.word');if(w)showPeek(w)});
  document.addEventListener('pointerdown',e=>{if(active&&!e.target.closest('.word')&&!e.target.closest('.verse-peek-bar'))clearPeek()});
  new MutationObserver(()=>{if(active&&!reader.querySelector('.word.verse-peek'))clearPeek()}).observe(reader,{childList:true,subtree:true});
})();